from tkinter import *
from tkinter.ttk import *

fenetre = Tk()
fenetre.minsize(width=600,height=350)
fenetre.maxsize(width=600,height=350)
tree = Treeview(fenetre,columns=('poids','gain'),)
tree.heading('poids',text='poids')
tree.heading('gain',text='gain')
tree.column('poids',width=120)
tree.column('gain',width=120)
tree.column('#0',width=150)
tree.pack()
tree.place(x=20,y=20)
tree.insert("", 0, text="Objet1", values=("1", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet1", values=("100", "20"))
tree.insert("", 0, text="Objet2", values=("100", "20"))
tree.insert("", 0, text="Objet3", values=("100", "20"))
fenetre.mainloop()